ReliMobileAdmin/Models/Warning.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReliMobileAdmin.Models
{
    public class Warning
    {
        private warning _dbWarning;
        public warning DBWarning
        {
            get
            {
                if (_dbWarning == null)
                {
                    _dbWarning = new warning();
                }
                return _dbWarning;
            }
            set
            {
                _dbWarning = value;
            }
        }

        public DateTime ReportedAt
        {
            get
            {
                return DBWarning.reportedAt;
            }
            set
            {
                DBWarning.reportedAt = value;
            }
        }

        public int warningId
        {
            get
            {
                return DBWarning.warningId;
            }
            set
            {
            }
        }
        public string warningTitle
        {
            get
            {
                return DBWarning.warningTitle;
            }
            set
            {
                DBWarning.warningTitle = value;
            }
        }

        public string warningContent
        {
            get
            {
                return DBWarning.warningMessage;
            }
            set
            {
                DBWarning.warningMessage = value;
            }
        }

        public Warning(warning dbWarning)
        {
            _dbWarning = dbWarning;
        }
        public Warning()
        {
        }
    }
}

ReliMobileAdmin/Controllers/WarningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReliMobileAdmin.Models;

namespace ReliMobileAdmin.Controllers
{
    [Authorize]
    public class WarningController : Controller
    {
        ReliMobileEntities context;

        public WarningController()
        {
            context = new ReliMobileEntities();
        }

        public ActionResult Index()
        {
            var warnings = context.warnings.Select(i => new Warning() { DBWarning = i });

            return View(warnings);
        }

        public ActionResult Create()
        {
            return View(new CreateWarningViewModel());
        }

        [HttpPost]
        public ActionResult Create(CreateWarningViewModel warningMV)
        {
            if (ModelState.IsValid)
            {
                var warning = new warning() { warningMessage = warningMV.WarningContent, warningTitle = warningMV.WarningTitle, reportedAt = DateTime.Now };
                context.warnings.AddObject(warning);
                context.SaveChanges();
                warningMV.IsCreated = true;
            }
            return View(warningMV);
        }

        [HttpDelete]
        public ActionResult Delete(int warningId)
        {
            var warning = context.warnings.Single(i => i.warningId == warningId);
            context.warnings.DeleteObject(warning);
            context.SaveChanges();
            return new JsonResult() { Data = "{ \" isDeleted \" : true } " };
        }
    }
}

ReliMobileAdmin/Views/Warning/Create.cshtml
@model ReliMobileAdmin.Models.CreateWarningViewModel

@{
    ViewBag.Title = "编写预警信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">

    <div class="row-fluid">
        <div class="box span12">
            <div class="box-header">
                <h2><i class="icon-edit"></i> 编写预警信息 </h2>
            </div>
            <div class="box-content">
            
                @if (Model.IsCreated.HasValue)
                {
                    if (Model.IsCreated.Value)
                    {
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <text>预警信息已发送</text>
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <text>未能发送预警信息，请稍后再试</text>
                        </div>
                    }
                }
                else
                {
                    if (Html.ValidationSummary().ToHtmlString().IndexOf("display:none") < 0)
                    {
                        <div class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            @Html.ValidationSummary()
                        </div>
                    }
                }

                @using (Html.BeginForm("Create", "Warning", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="control-group">
                        <label class="control-label"> 请填写标题 </label>
                        <div class="controls">

                            @Html.TextBoxFor(m => m.WarningTitle)
                            @Html.ValidationMessageFor(m => m.WarningTitle)

                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"> 预警内容 </label>
                        <div class="controls">
                            @Html.TextAreaFor(m => m.WarningContent, new { placeholder = "请输入您要填写的预警内容", @class = "diss-form span8", @rows = "8" })
                            @Html.ValidationMessageFor(m => m.WarningContent)
                        </div>
                    </div>
                    <div class="form-actions">
						<button type="submit" class="btn btn-primary btn-large span2">发送</button>
                        @Html.ActionLink("返回预警信息列表", "Index", "", new { @class = "btn  btn-large btn-inverse span4" })
                    </div>
                }
            </div>
        </div>
    </div>
    
</div>

ReliMobileAdmin/Views/Warning/Index.cshtml
@model IEnumerable<ReliMobileAdmin.Models.Warning>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>所有预警信息</h1>
<div class="row-fluid">


        <div class="box backgroundColor white">
            <table class="table table-bordered">
				<thead>
				<th>预警时间</th>
				<th>标题</th>
				<th>内容</th>
                <th>操作</th>
				</thead>
				<tbody>
                @foreach (var item in Model)
                {
                    <tr data-warningId="@item.warningId">
                        <td>@item.ReportedAt</td>
                        <td>@item.warningTitle</td>
                        <td>@item.warningContent</td>
                        <td>
                        <a class="btn btn-danger"><i class="icon-trash"></i></a></td>
                    </tr>
                }
				</tbody>
            </table>
        </div>

</div>

<script type="text/javascript">
    $(function () {
        $(".icon-trash, .btn-danger").click(function () {
            var $self = $(this);
            $.ajax({
                url: '/Warning/Delete',
                method: 'Delete',
                contentType: 'application/json',
                data: JSON.stringify({ "warningId": $self.parents('tr').attr("data-warningId") }),
                success: function (data) {
                    $self.parents('tr').fadeTo("slow", 0.00, function () {
                        $(this).slideUp("slow", function () {
                            $(this).remove();
                        });
                    });
                },
                error: function () {
                    alert("error");
                }
            });
        });
    });

</script>