ReliDemo/Models/Station.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using ReliDemo.Infrastructure.Helpers;
using ReliDemo.Infrastructure.Services;
using System.Data;

namespace ReliDemo.Models
{
    public partial class Station
    {
        public Station()
        {

        }
        public Station(IDataReader reader) {

        }
        public int StationId { get { return ItemID; }  }
        public string StationName { get; set; }
        public string StationCode { get; set; } // 热力站编号
        public string StationAbbr  { get; set; } // 热力站编码
        public string StationAddress { get; set; }
 
        public string 东西部
        {
            get
            {
                try
                {
                    return HeatSourceHelper.HeatSources.Find(i => i.生产热源ID == 生产热源ID).东西部;
                }
                catch
                {
                    return "";
                }
            }
        }

        public int? 数据来源ID
        {
            get
            {
                return StationsService.Get数据来源ID(_数据来源);
            }
        }

        public bool 是否为大网
        {
            get
            {
                return 生产热源ID == 1 || 生产热源ID == 22;
            }
        }
    }
}

ReliDemo/Controllers/StationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReliDemo.Models;
using ReliDemo.ViewModels;
using ReliDemo.Core.Interfaces;
using ReliDemo.Infrastructure.Repositories;
using ReliDemo.Infrastructure.Services;
using System.IO;
using OfficeOpenXml;
using ReliDemo.Infrastructure.Helpers;
using System.Configuration;

namespace ReliDemo.Controllers
{
    [Authorize]
    public class StationsController : Controller
    {
        private readonly IStationRepository _stationRepo;
        private readonly ICompanyRepository _companyRepo;
        private readonly IHeatSourceRepository _heatSourceRepo;
        private readonly IManagershipRepository _managershipRepo;
        private StationsService _stationsService;

        public StationsController(IStationRepository stationRepo, ICompanyRepository companyRepo, IHeatSourceRepository heatSourceRepo, IManagershipRepository managershipRepo)
        {
            _stationRepo = stationRepo;
            _companyRepo = companyRepo;
            _heatSourceRepo = heatSourceRepo;
            _managershipRepo = managershipRepo;
            _stationsService = new StationsService();

        }

        [HttpPost]
        public string GetManagershipsByCompanyId(int companyId)
        {
            var currentUser = MembershipService.CurrentUser;
            var allManagerships = _managershipRepo.GetAllManagerships();
            if (currentUser != null)
            {
                if (currentUser.是否有供热中心权限)
                {
                    allManagerships = allManagerships.Where(i => currentUser.VisibleManagerships.Exists(j => j.Id == i.ItemID));
                }
            }
            var managers = allManagerships.Where(i => i.公司ID == companyId || companyId == -1 ).Select(i => new { i.ItemID, i.管理单位 }).AsEnumerable().Select(i => string.Format("<option value='{0}' >{1}</option>", i.ItemID, i.管理单位));
            return string.Join("",managers);
        }

        public ActionResult Paged(int startIndex = 0, int pageSize = 10, int? area = null, int? heatSources = null, int? companies = null, int? managerships = null , 
            string keyword="", string 数据来源="", string 收费性质 = "", string 是否重点站 = "", string 是否故障站 = "")
        {
            var currentUser = MembershipService.CurrentUser;
            var allStations = _stationRepo.GetAllStations();
            if (currentUser != null)
            {
                if(currentUser.是否有分公司权限) {
                     allStations = allStations.Where(i=> currentUser.VisibleCompanies.Exists(j=>j.Id == i.公司ID));
                }
                else if(currentUser.是否有供热中心权限) {
                    allStations = allStations.Where(i=> currentUser.VisibleManagerships.Exists(j=>j.Id == i.管理单位ID));
                }
            }
            bool? nullable是否重点站 = null;
            if (是否重点站 == "0") 
            {
                nullable是否重点站 = false;
            }
            else if (是否重点站 == "1")
            {
                nullable是否重点站 = true;
            }

            bool? nullable是否故障站 = null;
            if (是否故障站 == "0")
            {
                nullable是否故障站 = false;
            }
            else if (是否故障站 == "1")
            {
                nullable是否故障站 = true;
            }

            var filteredStations = allStations.Where(i => (!heatSources.HasValue || (heatSources.HasValue && i.生产热源ID == heatSources)) &&
                                                          (!companies.HasValue || (companies.HasValue && i.公司ID == companies)) &&
                                                          (!managerships.HasValue || (managerships.HasValue && i.管理单位ID == managerships)) &&
                                                          (!area.HasValue || (i.东西部 == Enum.GetName( typeof(Region), area.Value)) ) &&
                                                          (string.IsNullOrEmpty(数据来源) || (i.数据来源 == 数据来源 || (i.数据来源 == null && 数据来源 == "人工抄表" ) ) ) &&
                                                          (string.IsNullOrEmpty(收费性质) || 收费性质 == i.收费性质) &&
                                                          (!nullable是否重点站.HasValue || nullable是否重点站.Value == i.是否重点站) &&
                                                          (!nullable是否故障站.HasValue || nullable是否故障站.Value == !string.IsNullOrEmpty(i.报警)) &&
                                                          (string.IsNullOrEmpty(keyword) || (!string.IsNullOrEmpty(keyword) &&
                                                          i.热力站名称!= null && i.热力站名称.IndexOf(keyword) >=0 )));
            
            var stationsViewModel = new StationsViewModel(filteredStations, startIndex, pageSize) 
            { 
                Companies = currentUser.VisibleCompanies, 
                HeatSources = _heatSourceRepo.GetAllHeatSources() ,
                SelectedManagershipId = managerships,
                SelectedCompanyId = companies,
                SelectedHeatSourceId = heatSources,
                SelectedRegion = area,
                SearchKeyword=keyword,
                是否重点站 = 是否重点站,
                数据来源 = 数据来源,
                收费性质 = 收费性质,
                是否故障站 = 是否故障站
            };
            ViewBag.Regions = Enum.GetValues(typeof(Region)).Cast<Region>().Select(i => new SelectListItem { Text = i.ToString(), Value = Convert.ToInt32(i).ToString(), Selected=Convert.ToInt32(i) == 2}).ToList();
            return View(stationsViewModel);
        }

        public ActionResult RealTime(int startIndex = 0, int pageSize = 10, int? regions = null, int? selectedHeatSourceId = null, int? selectedCompanyId = null, 
            int? managerships = null, int? selectedArea = null, string searchKeyWord="" , 
            decimal? exceedHeatFrom = null, decimal? exceedHeatTo = null, decimal? exceedWaterFrom = null, decimal? exceedWaterTo = null, decimal? exceedTemperatureFrom = null, decimal? exceedTemperatureTo = null)
        {
            var histories = _stationsService.GetStationsRealTime();

            var currentUser = MembershipService.CurrentUser;
            if (currentUser != null)
            {
                if (currentUser.是否有分公司权限)
                {
                    histories = histories.Where(i => currentUser.VisibleCompanies.Exists(j => j.Id == i.公司ID));
                }
                else if (currentUser.是否有供热中心权限)
                {
                    histories = histories.Where(i => currentUser.VisibleManagerships.Exists(j => j.Id == i.管理单位ID));
                }
            }
            
            histories = histories.Where(i => (!selectedHeatSourceId.HasValue || (selectedHeatSourceId.HasValue && i.生产热源ID == selectedHeatSourceId)) &&
                                                          (!selectedCompanyId.HasValue || (selectedCompanyId.HasValue && i.公司ID == selectedCompanyId)) &&
                                                          (!managerships.HasValue || (managerships.HasValue && i.管理单位ID == managerships)) &&
                                                          (!selectedArea.HasValue || (i.东西部 == Enum.GetName(typeof(Region), selectedArea.Value))) &&
                                                          (string.IsNullOrEmpty(searchKeyWord) || (!string.IsNullOrEmpty(searchKeyWord) && i.热力站名称 != null && i.热力站名称.IndexOf(searchKeyWord) >= 0)) &&
                                                          ((!exceedTemperatureFrom.HasValue) || (i.一次回温 >= exceedTemperatureFrom.Value && (exceedTemperatureTo == null || i.一次回温 <= exceedTemperatureTo.Value))));

            var stationsRealTimeViewModel = new StationsRealTimeViewModel(histories, startIndex, pageSize);
            stationsRealTimeViewModel.Companies = currentUser.VisibleCompanies;
            stationsRealTimeViewModel.HeatSources = _heatSourceRepo.GetAllHeatSources();
            stationsRealTimeViewModel.SelectedManagershipId = managerships;
            stationsRealTimeViewModel.SelectedCompanyId = selectedCompanyId;
            stationsRealTimeViewModel.SelectedHeatSourceId = selectedHeatSourceId;
            stationsRealTimeViewModel.SelectedArea = selectedArea;
            stationsRealTimeViewModel.SearchKeyword = searchKeyWord;
            stationsRealTimeViewModel.UpdatedAt = histories.Count() > 0 ? histories.First().采集时间 : null;
            stationsRealTimeViewModel.单耗超标From = exceedHeatFrom;
            stationsRealTimeViewModel.单耗超标To = exceedHeatTo;
            stationsRealTimeViewModel.流量超标From = exceedWaterFrom;
            stationsRealTimeViewModel.流量超标To = exceedWaterTo;
            stationsRealTimeViewModel.回温超标From = exceedTemperatureFrom;
            stationsRealTimeViewModel.回温超标To = exceedTemperatureTo;
            return View(stationsRealTimeViewModel);
        }

        

        public ActionResult Statistics(string searchSpan="yesterday", string date_customday="", string daterange="",string stat ="", int startIndex = 0, int pageSize = 10,
             string 热源="ALL", int? companies = null, int? managerships = null,
            int? 实际比核算From = null, int? 实际比核算To = null, int? 实际比计划From = null, int? 实际比计划To = null,
            string 收费性质="", int 是否重点站=2, string 数据来源="ALL")
        {
            int selectedSearchMethod = 1;
            DateTime fromdate = DateTime.Today;
            DateTime todate = DateTime.Today.AddDays(1);
            if (searchSpan == "yesterday")
            {
                fromdate = DateTime.Today.AddDays(-1);
                todate = fromdate;
            }
            else if (searchSpan == "last2day")
            {
                fromdate = DateTime.Today.AddDays(-2);
                todate = fromdate;
            }
            else if (searchSpan == "customday")
            {
                if (!string.IsNullOrEmpty(date_customday))
                {
                    fromdate = DateTime.Parse(date_customday);
                    todate = fromdate;
                }

ReliDemo/Views/Stations/HeatIndexHistory.cshtml
@model ReliDemo.ViewModels.HeatIndexHistoryViewModel

@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">
<div class="span8">
<p>
    @Html.ActionLink("返回热力站", "StationRealTime", new  { stationId = @Model.StationId }, new { @class = "btn btn-primary"})
</p>
</div>
</div>
<div class="row-fluid clearfix stationTitle">
    <h1>热力站名称</h1>
</div>

<table class="table  table-bordered table-hover  table-condensed table-clickhighlight datatable" style="background:white">
    <thead><tr>
		<th>时间</th>
		<th>热指标(Kcal/h*㎡)</th>
		<th>修改人</th>
    </tr></thead>
	<tbody>
        @foreach (var heatIndexAudit in Model.HeatIndexes)
        {
        <tr>
		    <td> @heatIndexAudit.UpdatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
		    <td> @heatIndexAudit.参考热指标</td>
		    <td> @heatIndexAudit.User.FullName </td>
        </tr>
        }
	</tbody>

</table>

ReliDemo/Views/Stations/History.cshtml
@model ReliDemo.ViewModels.StationHistoriesViewModel

@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">
<div class="span8">
<p>
    @Html.ActionLink("返回热力站列表", "Paged", new object { }, new { @class = "btn btn-primary"})
</p>
</div>
</div>
<div class="row-fluid clearfix stationTitle">
    <h1 class="span6">@Model.StationName
	@if ( string.IsNullOrEmpty( Model.数据来源 ) ) {
		<span class="label label-info"><i class="icon-pencil"></i> 人工抄表站</span> 
	} else {
		<span class="label label-important"><i class="icon-eye-open"></i> @Model.数据来源</span>
	}</h1>
     <div class="span6" onDesktop="span6" onTablet="span12 noMarginLeft">@Html.Partial("_TopMenu")</div>
</div>
<div class="row-fluid">
    @using (Html.BeginForm("History", "Stations", FormMethod.Get)) {
        <div class="input-prepend date" >
			<span class="add-on"><i class="icon-calendar"></i></span>
            <input type="text" class="form-control input-xlarge" id="daterange" name="daterange" value="@Model.FromDate.Value.ToString("yyyy年MM月dd日") - @Model.ToDate.Value.ToString("yyyy年MM月dd日") "  >
		</div>
        <input type="submit" value="搜索" class="btn btn-primary" style="vertical-align: top;"/>
        @Html.HiddenFor(m=>m.StationId)
    }
</div>
<div class="alert alert-info clearfix">
<div style="display:inline-block;float:left;position:relative;top:5px;">查询结果：历史记录 @Model.StationAccuHistories.TotalCount 个。 每页显示：</div>
<ul class="nav nav-pills" id="pills" style="float:left;display:inline-block;margin-bottom:0;">
<li @if (Model.StationAccuHistories.PageSize == 10)
    {
    <text> class="active" </text> 
    } >
    @Html.ActionLink("10", "History", new { pageIndex = Model.StationAccuHistories.PageIndex, pageSize = 10, stationId = @Model.StationId, daterange = string.Format("{0:yyyy年MM月dd日} - {1:yyyy年MM月dd日}", Model.FromDate, Model.ToDate) })
</li>
<li @if (Model.StationAccuHistories.PageSize == 50)
    {
    <text> class="active" </text> 
    } >
    @Html.ActionLink("50", "History", new { pageIndex = Model.StationAccuHistories.PageIndex, pageSize = 50, stationId = @Model.StationId, daterange = string.Format("{0:yyyy年MM月dd日} - {1:yyyy年MM月dd日}", Model.FromDate, Model.ToDate) })
</li>
<li @if (Model.StationAccuHistories.PageSize == 100)
    {
    <text> class="active" </text> 
    }>
    @Html.ActionLink("100", "History", new { pageIndex = Model.StationAccuHistories.PageIndex, pageSize = 100, stationId = @Model.StationId, daterange = string.Format("{0:yyyy年MM月dd日} - {1:yyyy年MM月dd日}", Model.FromDate, Model.ToDate) })
</li>
</ul>

</div>

<div class="rolw-fluid">
<div class="scrollableTableContainer">
<table class="table  table-bordered table-hover  table-condensed table-clickhighlight datatable" style="background:white">
	<thead>
    <tr>
        <th>日期</th>
        <th>投入面积 <span class="symbol">(㎡)</span></th>
        <th>计划供热量 <span class="symbol">(GJ)</span></th>
        <th>核算供热量 <span class="symbol">(GJ)</span></th>
        <th>实际供热量 <span class="symbol">(GJ)</span></th>
        <th>热水 <span class="symbol">(GJ)</span></th>
        <th>计算热指标 <span class="symbol">(kcal/h·㎡)</span></th>
        <th>计划热指标 <span class="symbol">(kcal/h·㎡)</span></th>
        <th>核算热指标 <span class="symbol">(kcal/h·㎡)</span></th>
        <th>实际热指标 <span class="symbol">(kcal/h·㎡)</span></th>
        <th>实际比计划多耗 <span class="symbol">(GJ)</span></th>
        <th>实际比计划多耗% <span class="symbol">(GJ)</span></th>
        <th>实际比核算多耗 <span class="symbol">(GJ)</span></th>
        <th>实际比核算多耗% <span class="symbol">(GJ)</span></th>
        <th>预报温度 <span class="symbol">(℃)</span></th>
        <th>实际温度 <span class="symbol">(℃)</span></th>
    </tr></thead>
	<tbody>
    @foreach (var history in Model.StationAccuHistories)
    {
        <tr>
            <td class="time">@history.Date.ToString("yyyy-MM-dd")</td>
            <td>@history.投入面积</td>
            <td>@history.计划供热量</td>
            <td>@history.核算供热量</td>
            <td>@history.实际采暖</td>
            <td>@history.实际热水</td>
            <td>@history.计算热指标</td>
            <td>@history.计划热指标</td>
            <td>@history.核算热指标</td>
            <td>@history.实际热指标</td>
            <td>@history.实际比计划多耗</td>
            <td>@String.Format("{0:0.00}",history.实际比计划多耗percent)</td>
            <td>@history.实际比核算多耗</td>
            <td>@String.Format("{0:0.00}", history.实际比核算多耗percent)</td>
            <td>@history.预报温度</td>
            <td>@history.实际温度</td>
        </tr>
    }
 </tbody>
</table>
</div>
</div>

<div class="row-fluid">
<div class="pagination pagination-centered">
    <ul>
       
        @if (Model.StationAccuHistories.PageIndex >= 10)
        {
            <li>@Html.ActionLink("« 前十页", "History", new { pageIndex = Model.StationAccuHistories.PageIndex - 10, pageSize = 10, stationId = Model.StationId, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        }
		 <li>@Html.ActionLink("« 上一页", "History", new { pageIndex = Model.StationAccuHistories.PageIndex - 1, pageSize = Model.StationAccuHistories.PageSize, stationId = Model.StationId, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        @for (int i = Model.StationAccuHistories.PageIndex / 10 * 10; (i < Model.StationAccuHistories.PageIndex / 10 * 10 + 10) && i < Model.StationAccuHistories.TotalPages; i++)
        {
            <li @if (Model.StationAccuHistories.PageIndex == i)
                { <text>class="active"</text> } >

                @Html.ActionLink((i + 1).ToString(), "History", new { pageIndex = i, pageSize = Model.StationAccuHistories.PageSize, stationId = Model.StationId, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })
            </li>
        }
		<li>@Html.ActionLink("下一页 »", "History", new { pageIndex = Model.StationAccuHistories.PageIndex + 1, pageSize = Model.StationAccuHistories.PageSize, stationId = Model.StationId, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        @if (Model.StationAccuHistories.PageIndex < Model.StationAccuHistories.TotalPages - 10)
        {
            <li>@Html.ActionLink("后十页 »", "History", new { pageIndex = (Model.StationAccuHistories.PageIndex / 10 + 1) * 10, pageSize = Model.StationAccuHistories.PageSize, stationId = Model.StationId, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        }
       
    </ul>
</div>
</div>

<script>
    $(function () {
        $("#daterange").daterangepicker({
            format: 'YYYY年MM月DD日',
            locale: {
                applyLabel: '确定',
                cancelLabel: '取消',
                fromLabel: '从',
                toLabel: '到',
                weekLabel: 'W',
                customRangeLabel: '自定义日期',
                daysOfWeek: moment()._lang._weekdaysMin.slice(),
                monthNames: moment()._lang._monthsShort.slice(),
                firstDay: 0
            }
        },
        function (start, end) {
            $("#customAll").attr("checked", "checked").parent().addClass("checked");
        });
    });
</script>

ReliDemo/Views/Stations/ManualDataInput.cshtml
@model ReliDemo.ViewModels.ManualDataInputViewModel

@{
    ViewBag.Title = "ManualDataInput";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    select 
    {
        width:100px;
    }
    input
    {
        width:50px;
    }
    .table td
    {
        vertical-align: bottom;
    }
</style>
<div class="row-fluid">
    <h1>人工抄表
    </h1>
    <div class="span8"></div>
</div>
<div class="row-fluid ">
    <div class="input-group col-sm-4">
    @using (Html.BeginForm("ManualDataInput", "Stations", FormMethod.Get))
    {
        @Html.DropDownListFor(model=>model.Selected生产编号, new SelectList(Model.Stations, "热力站编码", "热力站编码"), "生产编号检索", new { @class = "input-inline input-medium" })
        <text>&nbsp;</text>
        @Html.TextBox("stationName", @Model.热力站名称, new { placeholder = "热力站名称检索", @class = "input-inline  input-medium" })
        <text>&nbsp;</text>
        @Html.DropDownList("热力站编号", new SelectList(Model.Stations, "热力站编码", "热力站编码"), "热表编号", new { @class = "input-inline input-medium" })
        <text>&nbsp;</text>
        @Html.TextBox("errorDescription", @Model.故障状态, new { @class = "input-inline input-medium" , placeholder = "故障状态"})
        <text>&nbsp;</text>
		<div class="input-prepend">
        <span class="input-group-addon"><i class="icon-calendar"></i></span>
		<input type="text" class="form-control input-xlarge input-inline" id="daterange" name="daterange" value='@if(Model.FromDate.HasValue) {<text> @string.Format("{0:yyyy年MM月dd日} - {1:yyyy年MM月dd日}", Model.FromDate, Model.ToDate) </text>}' />
        </div>
        <input type="submit" value="搜索" class="btn  btn-primary input-inline" style="vertical-align: top;"/>
    }

    @using (Html.BeginForm("UploadManualDataInput", "Stations", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"  />
        <input type="submit" value="上传文件" class="btn btn-primary" />
    }
    </div>
</div>
<div class="row-fluid">
        每页显示：
<ul class="nav nav-pills" id="pills">
<li @if (Model.StationManualInput.PageSize == 10)
    {
    <text> class="active" </text> 
    } >
    @Html.ActionLink("10", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex, pageSize = 10, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })
</li>
<li @if (Model.StationManualInput.PageSize == 50)
    {
    <text> class="active" </text> 
    } >
    @Html.ActionLink("50", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex, pageSize = 50, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })
</li>
<li @if (Model.StationManualInput.PageSize == 100)
    {
    <text> class="active" </text> 
    }>
    @Html.ActionLink("100", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex, pageSize = 100, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })
</li>

</ul>
</div>
<div class="row-fluid">
<div class="scrollableTableContainer">
<table class="table  table-bordered table-hover  table-condensed table-clickhighlight datatable" style="background:white">
        <thead><tr>
            <th>生产编号</th>
            <th>热力站名称</th>
            <th>采集时间</th>
            <th>供压</th>
            <th>回压</th>
            <th>供温</th>
            <th>回温</th>
            <th>瞬时流量</th>
            <th>瞬时热量</th>
            <th>累计流量</th>
            <th>流量差量</th>
            <th>累计热量</th>
            <th>热量差量</th>
            <th>热指标</th>
            <th>站内面积</th>
            <th>部门</th>
            <th>管理方式</th>
            <th>管理单位</th>
            <th>有无生活水</th>
            <th>故障状态</th>
        </tr>
		</thead>
        @foreach (var manualInput in Model.StationManualInput)
        {
            <tr>
                <td> @manualInput.生产编号</td>
                <td> @manualInput.站名</td>
                <td> @manualInput.采集时间</td>
                <td> @manualInput.供压</td>
                <td> @manualInput.回压</td>
                <td> @manualInput.供温</td>
                <td> @manualInput.回温</td>
                <td> @manualInput.瞬流</td>
                <td> @manualInput.瞬热</td>
                <td> @manualInput.累计流量</td>
                <td> @manualInput.流量差量</td>
                <td> @manualInput.累计热量</td>
                <td> @manualInput.热量差量</td>
                <td> @manualInput.热指标</td>
                <td> @manualInput.站内面积</td>
                <td> @manualInput.部门</td>
                <td> @manualInput.管理方式</td>
                <td> @manualInput.管理单位</td>
                <td> @manualInput.有无生活水</td>
                <td> @manualInput.故障</td>
            </tr>
        }
    </table>
	</div>
</div>
<div class="row-fluid">
<div class="pagination pagination-centered">
    <ul>
       
        @if (Model.StationManualInput.PageIndex >= 10)
        {
            <li>@Html.ActionLink("« 前十页", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex - 10, pageSize = 10, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        }
		 <li>@Html.ActionLink("« 上一页", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex - 1, pageSize = Model.StationManualInput.PageSize, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        @for (int i = Model.StationManualInput.PageIndex / 10 * 10; (i < Model.StationManualInput.PageIndex / 10 * 10 + 10) && i < Model.StationManualInput.TotalPages; i++)
        {
            <li @if (Model.StationManualInput.PageIndex == i)
                { <text>class="active"</text> } >

                @Html.ActionLink((i + 1).ToString(), "ManualDataInput", new { pageIndex = i, pageSize = Model.StationManualInput.PageSize, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })
            </li>
        }
		<li>@Html.ActionLink("下一页 »", "ManualDataInput", new { pageIndex = Model.StationManualInput.PageIndex + 1, pageSize = Model.StationManualInput.PageSize, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate) })</li>
        @if (Model.StationManualInput.PageIndex < Model.StationManualInput.TotalPages - 10)
        {
            <li>@Html.ActionLink("后十页 »", "ManualDataInput", new { pageIndex = (Model.StationManualInput.PageIndex / 10 + 1) * 10, pageSize = Model.StationManualInput.PageSize, code = Model.Selected生产编号, stationName = Model.热力站名称, errorDescirption = Model.故障状态, daterange = string.Format("{0} - {1}", Model.FromDate, Model.ToDate)})</li>
        }
       
    </ul>
</div>
</div>
<script>

    $(function () {
        $("#daterange").daterangepicker({
            format: 'YYYY年MM月DD日',
            locale: {
                applyLabel: '确定',
                cancelLabel: '取消',
                fromLabel: '从',
                toLabel: '到',
                weekLabel: 'W',
                customRangeLabel: '自定义日期',
                daysOfWeek: moment()._lang._weekdaysMin.slice(),
                monthNames: moment()._lang._monthsShort.slice(),
                firstDay: 0
            }
        });
    });
</script>