ReliDemo/Models/HeatSource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReliDemo.Core.Interfaces;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;

namespace ReliDemo.Models
{
    public partial class HeatSource : IHeatSource 

    {
        public int HeatSourceId
        {
            get
            {
                return this.ItemID;
            }
            set
            {
            }
        }

        public string HeatSourceName
        {
            get
            {
                return this.热源名称;
            }
            set
            {
            }
        }

        public decimal? TemperatureIn
        {
            get
            {
                return this.HeatSourceRecents.OrderByDescending(i => i.采集时间).First().回温;
            }
            set
            {
            }
        }

        public decimal? TemperatureOut
        {
            get
            {
                return this.HeatSourceRecents.OrderByDescending(i => i.采集时间).First().供温;
            }
            set
            {
            }
        }

        public decimal? PressureIn
        {
            get
            {
                return this.HeatSourceRecents.OrderByDescending(i => i.采集时间).First().回压;
            }
            set
            {
            }
        }

        public decimal? PressureOut
        {
            get
            {
                return this.HeatSourceRecents.OrderByDescending(i => i.采集时间).First().供压;
            }
            set
            {
            }
        }

        public DateTime? LastUpdatedAt
        {
            get
            {
                return this.HeatSourceRecents.OrderByDescending(i => i.采集时间).First().采集时间;
            }
            set
            {
            }
        }
    }
}

ReliDemo/ViewModels/HeatSourceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReliDemo.Models;

namespace ReliDemo.ViewModels
{
    public class CostViewModel
    {
        public int TodayGJ { get; set; }
        public int TodayCoalGJ { get; set; }
        public int TodayGasGJ { get; set; }
        public int YesterdayGJ { get; set; }
        public int YesterdayCoalGJ { get; set; }
        public int YesterdayGasGJ { get; set; }
        public int SeasonGJ { get; set; }
        public int SeasonCoalGJ { get; set; }
        public int SeasonGasGJ { get; set; }
        public decimal TodayPrice { get; set; }
        public decimal TodayCoalPrice { get; set; }
        public decimal TodayGasPrice { get; set; }
        public decimal YesterdayPrice { get; set; }
        public decimal YesterdayCoalPrice { get; set; }
        public decimal YesterdayGasPrice { get; set; }
        public decimal SeasonPrice { get; set; }
        public decimal SeasonCoalPrice { get; set; }
        public decimal SeasonGasPrice { get; set; }
        public IEnumerable<HeatSourceRecent> HeatSourceRecents { get; set; }
    }

    public class HeatSourcesViewModel
    {
        public IEnumerable<HeatSource> HeatSources { get; set; }
        public decimal TotalFuelInSquareMeter { get; set; }
        public decimal EastFuelInSquareMeter { get; set; }
        public decimal WestFuelInSquareMeter { get; set; }
        public decimal FuelInFossil { get; set; }
        public decimal FuelInGas { get; set; }
        public decimal HeatSource { get; set; }
        public decimal PeakHeatSource { get; set; }
        public string HeatLoadsData { get; set; }
        public decimal TotalHeatLoad { get; set; }

        public HeatSourcesViewModel(IEnumerable<HeatSource> heatSources)
        {
            var db = new xz2013Entities();
            var total = db.TotalNetRecents.Single(i => i.ItemID == 3);
            var east = db.TotalNetRecents.Single(i => i.ItemID == 1);
            var west = db.TotalNetRecents.Single(i => i.ItemID == 2);
            var heatSourcesFull =   from heatSource in heatSources
                                    select new {
                                        Location = heatSource.东西部,
                                        Type = heatSource.机组类型,
                                        PeatHeatSource = heatSource.燃气尖峰炉数 + heatSource.燃煤尖峰炉数,
                                        HeatLoad = heatSource.Stations.Sum(i=>i.供暖季GJ),
                                        HeatSourceName = heatSource.热源名称
                                    };
            HeatSources = heatSources;
            TotalFuelInSquareMeter = Convert.ToDecimal(total.实际供热面积);
            EastFuelInSquareMeter = Convert.ToDecimal(east.实际供热面积);
            WestFuelInSquareMeter = Convert.ToDecimal(west.实际供热面积);
            FuelInFossil = 39.0m;
            FuelInGas = 61.0m;
            HeatLoadsData = "[" + string.Join(",", heatSourcesFull.Where(i=>i.HeatLoad>0).Select(i => string.Format("{{ \"label\" : \"{0}\", \"data\" : {1} }}", i.HeatSourceName,  i.HeatLoad)).ToList()) + "]";
            TotalHeatLoad = Convert.ToDecimal( total.供暖季累计GJ );
        }
    }

    public class HeatSourceViewModel
    {
        public int HeatSourceId {get;set;}
        public HeatSource HeatSource { get; set; }
    }

    public class HeatSourceHistoryViewModel
    {
        public int HeatSourceId { get; set; }
        public string HeatSourceName { get; set; }
        public IEnumerable<HeatSourceAccuHistory> Histories { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
    }

    public class HeatSourceRealTimeViewModel
    {
        public IEnumerable<ReliDemo.Models.HeatSourceRecent> HeatSourceRecents { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int SelectedRegion { get; set; }
        public int StartIndex { get; set; }
        public int PageSize { get; set; }
        public int TotalItemCount { get; set; }
    }
}

ReliDemo/Controllers/HeatSourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ReliDemo.Core.Interfaces;
using ReliDemo.ViewModels;
using ReliDemo.Infrastructure.Services;
using ReliDemo.Models;

namespace ReliDemo.Controllers
{
   // [Authorize]
    public class HeatSourcesController : Controller
    {
        private readonly IStationRepository _stationRepo;
        private readonly ICompanyRepository _companyRepo;
        private readonly IHeatSourceRepository _heatSourceRepo;
        private readonly IManagershipRepository _managershipRepo;
        private HeatSourcesService _heatSourcesService;
        
        public HeatSourcesController(IStationRepository stationRepo, ICompanyRepository companyRepo, IHeatSourceRepository heatSourceRepo, IManagershipRepository managershipRepo)
        {
            _stationRepo = stationRepo;
            _companyRepo = companyRepo;
            _heatSourceRepo = heatSourceRepo;
            _managershipRepo = managershipRepo;
            _heatSourcesService = new HeatSourcesService();
        }
        
        public ActionResult Index()
        {
            var heatSources = _heatSourceRepo.GetAllHeatSources();
            heatSources = heatSources.Where(j => j.是否并网供热 == true );
            return View( new HeatSourcesViewModel ( heatSources ) );
        }

        public ActionResult BasicInfo(int heatSourceId=0)
        {
            var heatSource = _heatSourceRepo.GetAllHeatSources().Single(i=>i.ItemID == heatSourceId);
            return View(new HeatSourceViewModel() { HeatSource = heatSource, HeatSourceId = heatSourceId } );
        }

        public ActionResult RealTime(int startIndex = 0, int pageSize = 10,int selectedRegion=1)
        {
            var total = _heatSourcesService.GetHeatSourcesRealTimeByRegion((HeatSourceRegions)selectedRegion);
            var heatSourceRecents = total.Skip(startIndex*pageSize).Take(pageSize).OrderByDescending(i=>i.采集时间);
            var heatSourceRealTimeViewModel = new HeatSourceRealTimeViewModel() {
                HeatSourceRecents = heatSourceRecents,
                SelectedRegion = selectedRegion,
                UpdatedAt = heatSourceRecents.Count() > 0 ? heatSourceRecents.First().采集时间 : null,
                StartIndex = startIndex,
                PageSize = pageSize,
                TotalItemCount = total.Count()
            };
            return View(heatSourceRealTimeViewModel);
        }
        
        public ActionResult History(int heatSourceId = 0,string daterange="")
        {
            var fromDate = DateTime.Now.AddDays(-7);
            var toDate = DateTime.Now;
            if (!string.IsNullOrEmpty(daterange))
            {
                var fromdate_todate = daterange.Split(new string[] { "-" }, StringSplitOptions.RemoveEmptyEntries);
                fromDate = DateTime.Parse(fromdate_todate[0]);
                toDate = DateTime.Parse(fromdate_todate[1]);
            }
            var heatSourceHistories = _heatSourcesService.GetHeatSourceHistory(heatSourceId,fromDate, toDate);
            var heatSource = _heatSourceRepo.GetAllHeatSources().Single(i => i.ItemID == heatSourceId);
            return View(new HeatSourceHistoryViewModel() { HeatSourceId = heatSourceId, Histories = heatSourceHistories, HeatSourceName = heatSource.热源名称 , FromDate = fromDate, ToDate = toDate});
        }

        public ActionResult GetNewDataCount(DateTime fromTime)
        {
            var newData = _heatSourcesService.GetHeatSourcesRealTime(fromTime, DateTime.Now);
            return Json(new { newDataCount = newData.Count() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddToTotalHeatSource(int heatSourceId = 11, bool isAddToTotal = true)
        {
            var heatSource = _heatSourceRepo.GetAllHeatSources().Single(i => i.ItemID == heatSourceId);
            heatSource.是否并网供热 = isAddToTotal;
            _heatSourceRepo.Update(heatSource);
            return RedirectToAction("BasicInfo", new { heatSourceId = heatSourceId });
        }

        public ActionResult ChangeHeatUnitPrice(FormCollection collection)
        {
            var heatSourceId = Convert.ToInt32(collection["heatSourceId"]);
            var prices = collection["price"].Split(',');
            var groupNumbers = collection["groupNumber"].Split(',');
            var heatSource = _heatSourceRepo.GetAllHeatSources().Single(i => i.ItemID == heatSourceId);
            for (int i=0;i< prices.Length;i++)
            {
                var price = Convert.ToDecimal(prices[i]);
                var groupNumber = Convert.ToInt32(groupNumbers[i]);
                heatSource.HeatSourceRecents.Single(j => j.机组号 == groupNumber).单价 = price;
            }
            _heatSourceRepo.Update(heatSource);
            return RedirectToAction("BasicInfo", new { heatSourceId = heatSourceId });
        }

        public ActionResult ChangeHeatSourceCapacity(FormCollection collection)
        {
            var heatSourceId = Convert.ToInt32(collection["heatSourceId"]);
            var heatSource = _heatSourceRepo.GetAllHeatSources().Single(i => i.ItemID == heatSourceId);
            if (heatSource.HeatsourceCapacity.Count == 0)
            {
                var heatsourceCapacity = new heatsourceCapacity() { 供热能力GJ = Convert.ToInt32(collection["gongrenengli"]), 已出力GJ = Convert.ToInt32(collection["yichuli"]) };
                heatSource.HeatsourceCapacity.Add(heatsourceCapacity);
            }
            else
            {
                heatSource.HeatsourceCapacity.First().供热能力GJ = Convert.ToInt32(collection["gongrenengli"]);
                heatSource.HeatsourceCapacity.First().已出力GJ = Convert.ToInt32(collection["yichuli"]);
            }
            _heatSourceRepo.Update(heatSource);
            return RedirectToAction("BasicInfo", new { heatSourceId = heatSourceId });
        }
    }
}

ReliDemo/Views/HeatSources/BasicInfo.cshtml
@model ReliDemo.ViewModels.HeatSourceViewModel

@{
    ViewBag.Title = "BasicInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    @Html.ActionLink("返回热源厂列表", "Index", new object { }, new { @class = "btn btn-primary"})
</p>
<div class="row-fluid clearfix stationTitle">
<h1 class="span3">@Model.HeatSource.热源名称</h1>
<div onDesktop="span4" onTablet="span6" onMobile="span12">@Html.Partial("_TopNav")</div>
</div>

<div class="row-fluid">
	<div class="box" onDesktop="span6" onTablet="span12">
		<div class="box-header">
		<h2><i class="icon-list"></i>基本信息</h2>
		</div>
		<div class="box-content" style="padding:25px">
			<table class="table table-bordered table-condensed">
			<tr>
			<th>热源名称</th><td colspan="3">@Model.HeatSource.热源名称</td>
			</tr>
			<tr>
			<th>区域</th><td>@Model.HeatSource.东西部</td>
			<th>组合方式</th><td>@Model.HeatSource.内外部</td>
			</tr>
			<tr>
			<th>机组总数</th><td>0</td>
			<th>机组类型</th><td>@Model.HeatSource.机组类型</td>
			</tr>
			<tr>
			<th>燃煤尖峰炉</th><td>@Model.HeatSource.燃煤尖峰炉数</td>
			<th>燃气尖峰炉</th><td>@Model.HeatSource.燃气尖峰炉数</td>
			</tr>
			<tr>
			<th>水线名称</th><td>@Model.HeatSource.水线名称</td>
			<th>蒸汽线名称</th><td>@Model.HeatSource.蒸汽线名称</td>
			</tr>
            <tr>
            <th>是否并网供热</th>
            <td >@Html.CheckBoxFor(m=>m.HeatSource.是否并网供热.Value)
            <td colspan="2">
            @if (ReliDemo.Infrastructure.Services.MembershipService.CurrentUser != null && ReliDemo.Infrastructure.Services.MembershipService.CurrentUser.是否有集团权限)
            {
            if (Model.HeatSourceId == 11 || Model.HeatSourceId == 5)
            {
                @Html.ActionLink(@Convert.ToBoolean(Model.HeatSource.是否并网供热) ? "加入独网" : "加入并网", "AddToTotalHeatSource", "HeatSources", new { heatSourceId = @Model.HeatSourceId, isAddToTotal = !@Convert.ToBoolean(Model.HeatSource.是否并网供热) }, new { @class = "btn btn-primary" }) 
            }
            }
            </td>
            </tr>
			</table>
		</div>
	</div><!--box--><!--span-->
	<div class="box" onDesktop="span6" onTablet="span12">
		<div class="box-header">
		<h2><i class="icon-fire"></i>供热能力</h2>
		</div>
		<div class="box-content">
			<div class="row-fluid">
				<div class="span4">
				<table class="table table-bordered table-condensed">
                    @using (Html.BeginForm("ChangeHeatSourceCapacity", "HeatSources", FormMethod.Post))
                    {
                        @Html.HiddenFor(m => m.HeatSourceId)
                        var heatsourceCapacity = @Model.HeatSource.HeatsourceCapacity.Count() > 0 ? @Model.HeatSource.HeatsourceCapacity.First() : null;
					    <tr><th>供热能力(GJ/h)</th></tr>
					    <tr><td > @Html.TextBox("gongrenengli", heatsourceCapacity != null ? heatsourceCapacity.供热能力GJ : 0, new { @class = "input-mini" }) </td></tr>
					    <tr><th>已出力(GJ/h)</th></tr>
					    <tr><td >@Html.TextBox("yichuli", heatsourceCapacity != null ? heatsourceCapacity.已出力GJ : 0, new { @class = "input-mini" })</td></tr>
					    <tr><th>出力％</th></tr>
					    <tr><td>@( heatsourceCapacity != null && heatsourceCapacity.供热能力GJ.HasValue && heatsourceCapacity.供热能力GJ.Value > 0 ? heatsourceCapacity.已出力GJ ?? 0 / heatsourceCapacity.供热能力GJ : 0)</td></tr>
                        if (ReliDemo.Infrastructure.Services.MembershipService.CurrentUser != null && ReliDemo.Infrastructure.Services.MembershipService.CurrentUser.是否有集团权限)
                        {
                        <tr><td><input value="修改供热能力" type="submit" class="btn btn-primary" /></td></tr>
                        }
                    }
				</table>
				</div>
				<div class="span8">
					<div id="heatsoursechart" style="height:150px">
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div><!--row-->
<div class="box" >
		<div class="box-header">
		<h2><i class="icon-tag"></i>机组列表及单价修改</h2>
		</div>
		<div class="box-content">
             @using (Html.BeginForm("ChangeHeatUnitPrice", "HeatSources", FormMethod.Post))
             {
                 @Html.HiddenFor(m => m.HeatSourceId)
			<table  class="table table-bordered table-condensed">
			<tr>
			<th>机组名</th>
			<th>机组号</th>
			<th>供暖季热价<span class="symbol">(元)</span></th>
			<th>今日热价<span class="symbol">(元)</span></th>
			<th>昨日热价<span class="symbol">(元)</span></th>
			<th>单价（元/GJ)</th>
			</tr>
            @foreach (var recent in @Model.HeatSource.HeatSourceRecents)
            {
                <tr>
                    <td>@recent.机组名</td>
                    <td>@recent.机组号 @Html.Hidden("groupNumber", recent.机组号)</td>
                    <td>@recent.供暖季热价</td>
                    <td>@recent.今日热价</td>
                    <td>@recent.昨日热价</td>
                    <td>@Html.TextBox("price", @recent.单价)</td>
                </tr>
            }
			</table>
            if (ReliDemo.Infrastructure.Services.MembershipService.CurrentUser != null && ReliDemo.Infrastructure.Services.MembershipService.CurrentUser.是否有集团权限)
            {
			<p style="margin-top:10px">
                <input type="submit" class="btn btn-primary" value="修改单价" />
            </p>
            }
             }
		</div>
	</div><!--box--><!--span-->
<div class="box">
	<div class="box-header">
	<h2><i class="icon-eye-open"></i>机组实时监测</h2>
	</div>
	<div class="box-content scrollableTableContainer">
		<table class="table table-bordered table-hover  table-condensed">
		<tr>
		<th>机组名</th>
		<th>机组号</th>
		<th>供温<span class="symbol">(℃)</span></th>
		<th>回温<span class="symbol">(℃)</span></th>
		<th>供压<span class="symbol">(MPa)</span></th>
		<th>回压<span class="symbol">(MPa)</span></th>
		<th>累计供水流量 <span class="symbol">(t)</span></th>
        <th>累计回水流量<span class="symbol">(t)</span></th>
		<th>累计供水热量<span class="symbol">(GJ)</span></th>
        <th>累计回水热量<span class="symbol">(GJ)</span></th>
		<th>累计热量<span class="symbol">(GJ)</span></th>
		<th>瞬时供水流量<span class="symbol">(t/h)</span></th>
        <th>瞬时回水流量<span class="symbol">(t/h)</span></th>
		<th>瞬时供水热量<span class="symbol">(GJ/h)</span></th>
        <th>瞬时回水热量<span class="symbol">(GJ/h)</span></th>
		<th>瞬时热量<span class="symbol">(GJ/h)</span></th>
		<th>瞬时补水量<span class="symbol">(t)</span></th>
		<th>累计补水量<span class="symbol">(t)</span></th>
		<th>采集时间</th>

        @foreach (var history in Model.HeatSource.HeatSourceRecents)
        {
            <tr>
                <td>@history.机组名</td>
                <td>@history.机组号</td>
                <td>@history.供温</td>
                <td>@history.回温</td>
                <td>@history.供压</td>
                <td>@history.回压</td>
                <td>@history.累计供水流量</td>
                <td>@history.累计回水流量</td>
                <td>@history.累计供水热量</td>
                <td>@history.累计回水热量</td>
                <td>@history.累计热量</td>
                <td>@history.瞬时供水流量</td>
                <td>@history.瞬时回水流量</td>
                <td>@history.瞬时供水热量</td>
                <td>@history.瞬时回水热量</td>
                <td>@history.瞬时热量</td>
                <td>@history.瞬时补水量</td>
                <td>@history.累计补水量</td>
                <td>@history.采集时间</td>
            </tr>
        }
		</tr>
		</table>
	</div>
</div><!--box-->

<script>
    $(function () {
        var yichuli = parseInt($("#yichuli").val());
        var gongrenengli = parseInt($("#gongrenengli").val());
        var shengyu = gongrenengli-yichuli;
        if(yichuli == 0){ yichuli =1;}
        if(shengyu == 0) {shengyu = 1;}
        var data = [{ label: "已出力(GJ/h)", data: yichuli }, { label: "剩余供热能力(GJ/h)", data: shengyu}];
        console.log(data);
        $.plot('#heatsoursechart', data, {
            series: {
                pie: {
                    show: true
                }
            }
        });
    });
</script>

ReliDemo/Views/HeatSources/History.cshtml
@{
    ViewBag.Title = "History";
}

@model ReliDemo.ViewModels.HeatSourceHistoryViewModel 

@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">
<div class="span8">
<p>
    @Html.ActionLink("返回热源厂实时监测", "RealTime", new object { }, new { @class = "btn btn-primary"})
</p>
</div>
</div>
<div class="row-fluid clearfix stationTitle">
    <h1 class="span3">@Model.HeatSourceName</h1>
    <div onDesktop="span4" onTablet="span6" onMobile="span12">@Html.Partial("_TopNav")</div>
</div>
<div class="row-fluid form-inline">
    @using (Html.BeginForm("History", "HeatSources", new { heatSourceId = @Model.HeatSourceId }, FormMethod.Get )) {
        <div class="input-prepend date" >
            <label>选择日期</label>
			<span class="add-on"><i class="icon-calendar"></i></span>
            <input type="text" class="form-control input-large" id="daterange" name="daterange" value="@Model.FromDate.Value.ToString("yyyy年MM月dd日") - @Model.ToDate.Value.ToString("yyyy年MM月dd日")"  >
		</div>
        @Html.HiddenFor(i=>i.HeatSourceId)
        <button type="submit" class="btn btn-primary" ><i class="icon-search"></i> 搜索</button>
    }
</div>

<div class="rolw-fluid">
<table class="table  table-bordered table-hover  table-condensed table-clickhighlight datatable" style="background:white">
		<thead><tr>
		<th>日期</th>
		<th>机组号</th>
		<th>日累计热量<span class="symbol">(GJ)</span></th>
        <th>供暖季<span class="symbol">(GJ)</span></th>
		</tr></thead>
        @foreach (var history in @Model.Histories)
        {
            <tr>

                <td>
                    @history.日期.ToShortDateString()
                </td>
                <td>
                    @history.机组号
                </td>
                <td>
                    @history.日累计热量
                </td>
                <td>
                    @history.供暖季GJ
                </td>
            </tr>
        }
		</table>
</div>

<script>
    $(function () {
        $("#daterange").daterangepicker({
            format: 'YYYY年MM月DD日',
            locale: {
                applyLabel: '确定',
                cancelLabel: '取消',
                fromLabel: '从',
                toLabel: '到',
                weekLabel: 'W',
                customRangeLabel: '自定义日期',
                daysOfWeek: moment()._lang._weekdaysMin.slice(),
                monthNames: moment()._lang._monthsShort.slice(),
                firstDay: 0
            }
        });
    });
</script>

ReliDemo/Views/HeatSources/HistoryDetail.cshtml
@{
    ViewBag.Title = "HistoryDetail";
}

<h2>HistoryDetail</h2>
<th>供温<span class="symbol">(℃)</span></th>
		<th>回温<span class="symbol">(℃)</span></th>
		<th>供压<span class="symbol">(MPa)</span></th>
		<th>回压<span class="symbol">(MPa)</span></th>
		<th>累计供水流量 <span class="symbol">(t/h)</span></th>
        <th>累计回水流量<span class="symbol">(t)</span></th>
		<th>累计供水热量<span class="symbol">(GJ)</span></th>
		<th>累计回水热量<span class="symbol">(GJ)</span></th>
		<th>瞬时供水流量<span class="symbol">(t/h)</span></th>
        <th>瞬时回水流量<span class="symbol">(t/h)</span></th>
		<th>瞬时供水热量<span class="symbol">(GJ/h)</span></th>
        <th>瞬时回水热量<span class="symbol">(GJ/h)</span></th>
		<th>累计热量<span class="symbol">(GJ)</span></th>
		<th>瞬时热量<span class="symbol">(GJ/h)</span></th>
		<th>累计补水量<span class="symbol">(t)</span></th>
        <th>瞬时补水量<span class="symbol">(t)</span></th>
		<th>当日<span class="symbol">(GJ)</span></th>

ReliDemo/Views/HeatSources/_TopMenu.cshtml
<div class='btn-group topmenu'>
    @Html.ActionLink("全网", "RealTime", new { selectedRegion = 1 }, new { @class = Model.SelectedRegion == 1 ? "btn selected" : "btn" })
    @Html.ActionLink("东部", "RealTime", new { selectedRegion = 2 }, new { @class = Model.SelectedRegion == 2 ? "btn selected" : "btn" })
    @Html.ActionLink("西部", "RealTime", new { selectedRegion = 3 }, new { @class = Model.SelectedRegion == 3 ? "btn selected" : "btn" })
    @Html.ActionLink("独网", "RealTime", new { selectedRegion = 4 }, new { @class = Model.SelectedRegion == 4 ? "btn selected" : "btn" })
</div>

ReliDemo/Views/HeatSources/_TopNav.cshtml
<div class='btn-group topmenu'>
    @Html.ActionLink("基础信息", "BasicInfo", new { heatSourceId = Model.HeatSourceId }, new { @class = ViewBag.Title == "BasicInfo" ? "btn selected" : "btn" })
    @Html.ActionLink("机组历史", "History", new { heatSourceId = Model.HeatSourceId }, new {@class = ViewBag.Title == "History" ? "btn selected" : "btn" })
</div>